/*
 * Pdf4me
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import model.KeyValuePairStringString;
import org.threeten.bp.OffsetDateTime;

/**
 * CustomerBO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-02T11:08:16.145Z")
public class CustomerBO {
  @SerializedName("customerId")
  private UUID customerId = null;

  @SerializedName("tenantId")
  private UUID tenantId = null;

  @SerializedName("subscriptionId")
  private UUID subscriptionId = null;

  @SerializedName("active")
  private Boolean active = null;

  /**
   * Gets or Sets pdf4meType
   */
  @JsonAdapter(Pdf4meTypeEnum.Adapter.class)
  public enum Pdf4meTypeEnum {
    UNDEF("undef"),

    API("api"),

    CONSUMER("consumer");

    private String value;

    Pdf4meTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static Pdf4meTypeEnum fromValue(String text) {
      for (Pdf4meTypeEnum b : Pdf4meTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<Pdf4meTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final Pdf4meTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public Pdf4meTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return Pdf4meTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("pdf4meType")
  private Pdf4meTypeEnum pdf4meType = null;

  @SerializedName("vat")
  private String vat = null;

  @SerializedName("countryCode")
  private String countryCode = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("language")
  private String language = null;

  @SerializedName("companyName")
  private String companyName = null;

  @SerializedName("firstName")
  private String firstName = null;

  @SerializedName("lastName")
  private String lastName = null;

  @SerializedName("street")
  private String street = null;

  @SerializedName("zip")
  private String zip = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("ipAdr")
  private String ipAdr = null;

  @SerializedName("creationDate")
  private OffsetDateTime creationDate = null;

  @SerializedName("creationName")
  private String creationName = null;

  @SerializedName("modDate")
  private OffsetDateTime modDate = null;

  @SerializedName("modName")
  private String modName = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("chargeBeeCustomerId")
  private String chargeBeeCustomerId = null;

  @SerializedName("validationRes")
  private List<KeyValuePairStringString> validationRes = null;

  public CustomerBO customerId(UUID customerId) {
    this.customerId = customerId;
    return this;
  }

  /**
   * Get customerId
   * 
   * @return customerId
   **/
  @ApiModelProperty(value = "")
  public UUID getCustomerId() {
    return customerId;
  }

  public void setCustomerId(UUID customerId) {
    this.customerId = customerId;
  }

  public CustomerBO tenantId(UUID tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Get tenantId
   * 
   * @return tenantId
   **/
  @ApiModelProperty(value = "")
  public UUID getTenantId() {
    return tenantId;
  }

  public void setTenantId(UUID tenantId) {
    this.tenantId = tenantId;
  }

  public CustomerBO subscriptionId(UUID subscriptionId) {
    this.subscriptionId = subscriptionId;
    return this;
  }

  /**
   * Get subscriptionId
   * 
   * @return subscriptionId
   **/
  @ApiModelProperty(value = "")
  public UUID getSubscriptionId() {
    return subscriptionId;
  }

  public void setSubscriptionId(UUID subscriptionId) {
    this.subscriptionId = subscriptionId;
  }

  public CustomerBO active(Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * 
   * @return active
   **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public CustomerBO pdf4meType(Pdf4meTypeEnum pdf4meType) {
    this.pdf4meType = pdf4meType;
    return this;
  }

  /**
   * Get pdf4meType
   * 
   * @return pdf4meType
   **/
  @ApiModelProperty(value = "")
  public Pdf4meTypeEnum getPdf4meType() {
    return pdf4meType;
  }

  public void setPdf4meType(Pdf4meTypeEnum pdf4meType) {
    this.pdf4meType = pdf4meType;
  }

  public CustomerBO vat(String vat) {
    this.vat = vat;
    return this;
  }

  /**
   * Get vat
   * 
   * @return vat
   **/
  @ApiModelProperty(value = "")
  public String getVat() {
    return vat;
  }

  public void setVat(String vat) {
    this.vat = vat;
  }

  public CustomerBO countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * Get countryCode
   * 
   * @return countryCode
   **/
  @ApiModelProperty(value = "")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public CustomerBO currency(String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * 
   * @return currency
   **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public CustomerBO language(String language) {
    this.language = language;
    return this;
  }

  /**
   * Get language
   * 
   * @return language
   **/
  @ApiModelProperty(value = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public CustomerBO companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

  /**
   * Get companyName
   * 
   * @return companyName
   **/
  @ApiModelProperty(value = "")
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public CustomerBO firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * Get firstName
   * 
   * @return firstName
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public CustomerBO lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * Get lastName
   * 
   * @return lastName
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public CustomerBO street(String street) {
    this.street = street;
    return this;
  }

  /**
   * Get street
   * 
   * @return street
   **/
  @ApiModelProperty(value = "")
  public String getStreet() {
    return street;
  }

  public void setStreet(String street) {
    this.street = street;
  }

  public CustomerBO zip(String zip) {
    this.zip = zip;
    return this;
  }

  /**
   * Get zip
   * 
   * @return zip
   **/
  @ApiModelProperty(value = "")
  public String getZip() {
    return zip;
  }

  public void setZip(String zip) {
    this.zip = zip;
  }

  public CustomerBO city(String city) {
    this.city = city;
    return this;
  }

  /**
   * Get city
   * 
   * @return city
   **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public CustomerBO ipAdr(String ipAdr) {
    this.ipAdr = ipAdr;
    return this;
  }

  /**
   * Get ipAdr
   * 
   * @return ipAdr
   **/
  @ApiModelProperty(value = "")
  public String getIpAdr() {
    return ipAdr;
  }

  public void setIpAdr(String ipAdr) {
    this.ipAdr = ipAdr;
  }

  public CustomerBO creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

  /**
   * Get creationDate
   * 
   * @return creationDate
   **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public CustomerBO creationName(String creationName) {
    this.creationName = creationName;
    return this;
  }

  /**
   * Get creationName
   * 
   * @return creationName
   **/
  @ApiModelProperty(value = "")
  public String getCreationName() {
    return creationName;
  }

  public void setCreationName(String creationName) {
    this.creationName = creationName;
  }

  public CustomerBO modDate(OffsetDateTime modDate) {
    this.modDate = modDate;
    return this;
  }

  /**
   * Get modDate
   * 
   * @return modDate
   **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getModDate() {
    return modDate;
  }

  public void setModDate(OffsetDateTime modDate) {
    this.modDate = modDate;
  }

  public CustomerBO modName(String modName) {
    this.modName = modName;
    return this;
  }

  /**
   * Get modName
   * 
   * @return modName
   **/
  @ApiModelProperty(value = "")
  public String getModName() {
    return modName;
  }

  public void setModName(String modName) {
    this.modName = modName;
  }

  public CustomerBO email(String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * 
   * @return email
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public CustomerBO chargeBeeCustomerId(String chargeBeeCustomerId) {
    this.chargeBeeCustomerId = chargeBeeCustomerId;
    return this;
  }

  /**
   * Get chargeBeeCustomerId
   * 
   * @return chargeBeeCustomerId
   **/
  @ApiModelProperty(value = "")
  public String getChargeBeeCustomerId() {
    return chargeBeeCustomerId;
  }

  public void setChargeBeeCustomerId(String chargeBeeCustomerId) {
    this.chargeBeeCustomerId = chargeBeeCustomerId;
  }

  public CustomerBO validationRes(List<KeyValuePairStringString> validationRes) {
    this.validationRes = validationRes;
    return this;
  }

  public CustomerBO addValidationResItem(KeyValuePairStringString validationResItem) {
    if (this.validationRes == null) {
      this.validationRes = new ArrayList<KeyValuePairStringString>();
    }
    this.validationRes.add(validationResItem);
    return this;
  }

  /**
   * Get validationRes
   * 
   * @return validationRes
   **/
  @ApiModelProperty(value = "")
  public List<KeyValuePairStringString> getValidationRes() {
    return validationRes;
  }

  public void setValidationRes(List<KeyValuePairStringString> validationRes) {
    this.validationRes = validationRes;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerBO customerBO = (CustomerBO) o;
    return Objects.equals(this.customerId, customerBO.customerId) && Objects.equals(this.tenantId, customerBO.tenantId)
        && Objects.equals(this.subscriptionId, customerBO.subscriptionId)
        && Objects.equals(this.active, customerBO.active) && Objects.equals(this.pdf4meType, customerBO.pdf4meType)
        && Objects.equals(this.vat, customerBO.vat) && Objects.equals(this.countryCode, customerBO.countryCode)
        && Objects.equals(this.currency, customerBO.currency) && Objects.equals(this.language, customerBO.language)
        && Objects.equals(this.companyName, customerBO.companyName)
        && Objects.equals(this.firstName, customerBO.firstName) && Objects.equals(this.lastName, customerBO.lastName)
        && Objects.equals(this.street, customerBO.street) && Objects.equals(this.zip, customerBO.zip)
        && Objects.equals(this.city, customerBO.city) && Objects.equals(this.ipAdr, customerBO.ipAdr)
        && Objects.equals(this.creationDate, customerBO.creationDate)
        && Objects.equals(this.creationName, customerBO.creationName)
        && Objects.equals(this.modDate, customerBO.modDate) && Objects.equals(this.modName, customerBO.modName)
        && Objects.equals(this.email, customerBO.email)
        && Objects.equals(this.chargeBeeCustomerId, customerBO.chargeBeeCustomerId)
        && Objects.equals(this.validationRes, customerBO.validationRes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, tenantId, subscriptionId, active, pdf4meType, vat, countryCode, currency, language,
        companyName, firstName, lastName, street, zip, city, ipAdr, creationDate, creationName, modDate, modName, email,
        chargeBeeCustomerId, validationRes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerBO {\n");

    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    subscriptionId: ").append(toIndentedString(subscriptionId)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    pdf4meType: ").append(toIndentedString(pdf4meType)).append("\n");
    sb.append("    vat: ").append(toIndentedString(vat)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    ipAdr: ").append(toIndentedString(ipAdr)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    creationName: ").append(toIndentedString(creationName)).append("\n");
    sb.append("    modDate: ").append(toIndentedString(modDate)).append("\n");
    sb.append("    modName: ").append(toIndentedString(modName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    chargeBeeCustomerId: ").append(toIndentedString(chargeBeeCustomerId)).append("\n");
    sb.append("    validationRes: ").append(toIndentedString(validationRes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
