/*
 * Pdf4me
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import model.DocLog;
import model.DocMetadata;
import model.Page;

/**
 * Document
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-25T12:07:57.015+01:00")
public class Document {
  @SerializedName("documentId")
  private String documentId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("fileName")
  private String fileName = null;

  @SerializedName("fileExtension")
  private String fileExtension = null;

  @SerializedName("docStatus")
  private String docStatus = null;

  @SerializedName("pages")
  private List<Page> pages = null;

  @SerializedName("docData")
  private byte[] docData = null;

  @SerializedName("docMetadata")
  private DocMetadata docMetadata = null;

  @SerializedName("docLogs")
  private List<DocLog> docLogs = null;

  @SerializedName("documentUrl")
  private String documentUrl = null;

  public Document documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * DocumentId
   * @return documentId
  **/
  @ApiModelProperty(value = "DocumentId")
  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public Document name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Give filename inlcuding filetype
   * @return name
  **/
  @ApiModelProperty(value = "Give filename inlcuding filetype")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Document fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName
  **/
  @ApiModelProperty(value = "")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public Document fileExtension(String fileExtension) {
    this.fileExtension = fileExtension;
    return this;
  }

   /**
   * Get fileExtension
   * @return fileExtension
  **/
  @ApiModelProperty(value = "")
  public String getFileExtension() {
    return fileExtension;
  }

  public void setFileExtension(String fileExtension) {
    this.fileExtension = fileExtension;
  }

  public Document docStatus(String docStatus) {
    this.docStatus = docStatus;
    return this;
  }

   /**
   * Returns the Status of the Document
   * @return docStatus
  **/
  @ApiModelProperty(value = "Returns the Status of the Document")
  public String getDocStatus() {
    return docStatus;
  }

  public void setDocStatus(String docStatus) {
    this.docStatus = docStatus;
  }

  public Document pages(List<Page> pages) {
    this.pages = pages;
    return this;
  }

  public Document addPagesItem(Page pagesItem) {
    if (this.pages == null) {
      this.pages = new ArrayList<Page>();
    }
    this.pages.add(pagesItem);
    return this;
  }

   /**
   * Description of pages
   * @return pages
  **/
  @ApiModelProperty(value = "Description of pages")
  public List<Page> getPages() {
    return pages;
  }

  public void setPages(List<Page> pages) {
    this.pages = pages;
  }

  public Document docData(byte[] docData) {
    this.docData = docData;
    return this;
  }

   /**
   * Get docData
   * @return docData
  **/
  @ApiModelProperty(value = "")
  public byte[] getDocData() {
    return docData;
  }

  public void setDocData(byte[] docData) {
    this.docData = docData;
  }

  public Document docMetadata(DocMetadata docMetadata) {
    this.docMetadata = docMetadata;
    return this;
  }

   /**
   * Get docMetadata
   * @return docMetadata
  **/
  @ApiModelProperty(value = "")
  public DocMetadata getDocMetadata() {
    return docMetadata;
  }

  public void setDocMetadata(DocMetadata docMetadata) {
    this.docMetadata = docMetadata;
  }

  public Document docLogs(List<DocLog> docLogs) {
    this.docLogs = docLogs;
    return this;
  }

  public Document addDocLogsItem(DocLog docLogsItem) {
    if (this.docLogs == null) {
      this.docLogs = new ArrayList<DocLog>();
    }
    this.docLogs.add(docLogsItem);
    return this;
  }

   /**
   * Get docLogs
   * @return docLogs
  **/
  @ApiModelProperty(value = "")
  public List<DocLog> getDocLogs() {
    return docLogs;
  }

  public void setDocLogs(List<DocLog> docLogs) {
    this.docLogs = docLogs;
  }

  public Document documentUrl(String documentUrl) {
    this.documentUrl = documentUrl;
    return this;
  }

   /**
   * Get documentUrl
   * @return documentUrl
  **/
  @ApiModelProperty(value = "")
  public String getDocumentUrl() {
    return documentUrl;
  }

  public void setDocumentUrl(String documentUrl) {
    this.documentUrl = documentUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Document document = (Document) o;
    return Objects.equals(this.documentId, document.documentId) &&
        Objects.equals(this.name, document.name) &&
        Objects.equals(this.fileName, document.fileName) &&
        Objects.equals(this.fileExtension, document.fileExtension) &&
        Objects.equals(this.docStatus, document.docStatus) &&
        Objects.equals(this.pages, document.pages) &&
        Objects.equals(this.docData, document.docData) &&
        Objects.equals(this.docMetadata, document.docMetadata) &&
        Objects.equals(this.docLogs, document.docLogs) &&
        Objects.equals(this.documentUrl, document.documentUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentId, name, fileName, fileExtension, docStatus, pages, docData, docMetadata, docLogs, documentUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Document {\n");
    
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    fileExtension: ").append(toIndentedString(fileExtension)).append("\n");
    sb.append("    docStatus: ").append(toIndentedString(docStatus)).append("\n");
    sb.append("    pages: ").append(toIndentedString(pages)).append("\n");
    sb.append("    docData: ").append(toIndentedString(docData)).append("\n");
    sb.append("    docMetadata: ").append(toIndentedString(docMetadata)).append("\n");
    sb.append("    docLogs: ").append(toIndentedString(docLogs)).append("\n");
    sb.append("    documentUrl: ").append(toIndentedString(documentUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

