/*
 * DmsApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * ExecutionTrigger
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-01T18:17:38.351+01:00")
public class ExecutionTrigger {
  @SerializedName("startTime")
  private OffsetDateTime startTime = null;

  @SerializedName("cronTrigger")
  private String cronTrigger = null;

  @SerializedName("continues")
  private Boolean continues = null;

  public ExecutionTrigger startTime(OffsetDateTime startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }

  public ExecutionTrigger cronTrigger(String cronTrigger) {
    this.cronTrigger = cronTrigger;
    return this;
  }

   /**
   * Get cronTrigger
   * @return cronTrigger
  **/
  @ApiModelProperty(value = "")
  public String getCronTrigger() {
    return cronTrigger;
  }

  public void setCronTrigger(String cronTrigger) {
    this.cronTrigger = cronTrigger;
  }

  public ExecutionTrigger continues(Boolean continues) {
    this.continues = continues;
    return this;
  }

   /**
   * Get continues
   * @return continues
  **/
  @ApiModelProperty(value = "")
  public Boolean isContinues() {
    return continues;
  }

  public void setContinues(Boolean continues) {
    this.continues = continues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecutionTrigger executionTrigger = (ExecutionTrigger) o;
    return Objects.equals(this.startTime, executionTrigger.startTime) &&
        Objects.equals(this.cronTrigger, executionTrigger.cronTrigger) &&
        Objects.equals(this.continues, executionTrigger.continues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startTime, cronTrigger, continues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecutionTrigger {\n");
    
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    cronTrigger: ").append(toIndentedString(cronTrigger)).append("\n");
    sb.append("    continues: ").append(toIndentedString(continues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

