/*
 * Pdf4me
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import model.DocLog;
import model.DocMetadata;
import model.Pdf4meDocument;

/**
 * GetDocumentListRes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-25T12:07:57.015+01:00")
public class GetDocumentListRes {
  @SerializedName("jobId")
  private UUID jobId = null;

  @SerializedName("jobIdExt")
  private String jobIdExt = null;

  @SerializedName("docLogs")
  private List<DocLog> docLogs = null;

  @SerializedName("documentList")
  private List<Pdf4meDocument> documentList = null;

  @SerializedName("document")
  private Pdf4meDocument document = null;

  @SerializedName("inDocMetadata")
  private DocMetadata inDocMetadata = null;

  @SerializedName("inDocMetadataList")
  private List<DocMetadata> inDocMetadataList = null;

  public GetDocumentListRes jobId(UUID jobId) {
    this.jobId = jobId;
    return this;
  }

   /**
   * Get jobId
   * @return jobId
  **/
  @ApiModelProperty(value = "")
  public UUID getJobId() {
    return jobId;
  }

  public void setJobId(UUID jobId) {
    this.jobId = jobId;
  }

  public GetDocumentListRes jobIdExt(String jobIdExt) {
    this.jobIdExt = jobIdExt;
    return this;
  }

   /**
   * Get jobIdExt
   * @return jobIdExt
  **/
  @ApiModelProperty(value = "")
  public String getJobIdExt() {
    return jobIdExt;
  }

  public void setJobIdExt(String jobIdExt) {
    this.jobIdExt = jobIdExt;
  }

  public GetDocumentListRes docLogs(List<DocLog> docLogs) {
    this.docLogs = docLogs;
    return this;
  }

  public GetDocumentListRes addDocLogsItem(DocLog docLogsItem) {
    if (this.docLogs == null) {
      this.docLogs = new ArrayList<DocLog>();
    }
    this.docLogs.add(docLogsItem);
    return this;
  }

   /**
   * Get docLogs
   * @return docLogs
  **/
  @ApiModelProperty(value = "")
  public List<DocLog> getDocLogs() {
    return docLogs;
  }

  public void setDocLogs(List<DocLog> docLogs) {
    this.docLogs = docLogs;
  }

  public GetDocumentListRes documentList(List<Pdf4meDocument> documentList) {
    this.documentList = documentList;
    return this;
  }

  public GetDocumentListRes addDocumentListItem(Pdf4meDocument documentListItem) {
    if (this.documentList == null) {
      this.documentList = new ArrayList<Pdf4meDocument>();
    }
    this.documentList.add(documentListItem);
    return this;
  }

   /**
   * Get documentList
   * @return documentList
  **/
  @ApiModelProperty(value = "")
  public List<Pdf4meDocument> getDocumentList() {
    return documentList;
  }

  public void setDocumentList(List<Pdf4meDocument> documentList) {
    this.documentList = documentList;
  }

  public GetDocumentListRes document(Pdf4meDocument document) {
    this.document = document;
    return this;
  }

   /**
   * Get document
   * @return document
  **/
  @ApiModelProperty(value = "")
  public Pdf4meDocument getDocument() {
    return document;
  }

  public void setDocument(Pdf4meDocument document) {
    this.document = document;
  }

  public GetDocumentListRes inDocMetadata(DocMetadata inDocMetadata) {
    this.inDocMetadata = inDocMetadata;
    return this;
  }

   /**
   * Get inDocMetadata
   * @return inDocMetadata
  **/
  @ApiModelProperty(value = "")
  public DocMetadata getInDocMetadata() {
    return inDocMetadata;
  }

  public void setInDocMetadata(DocMetadata inDocMetadata) {
    this.inDocMetadata = inDocMetadata;
  }

  public GetDocumentListRes inDocMetadataList(List<DocMetadata> inDocMetadataList) {
    this.inDocMetadataList = inDocMetadataList;
    return this;
  }

  public GetDocumentListRes addInDocMetadataListItem(DocMetadata inDocMetadataListItem) {
    if (this.inDocMetadataList == null) {
      this.inDocMetadataList = new ArrayList<DocMetadata>();
    }
    this.inDocMetadataList.add(inDocMetadataListItem);
    return this;
  }

   /**
   * Get inDocMetadataList
   * @return inDocMetadataList
  **/
  @ApiModelProperty(value = "")
  public List<DocMetadata> getInDocMetadataList() {
    return inDocMetadataList;
  }

  public void setInDocMetadataList(List<DocMetadata> inDocMetadataList) {
    this.inDocMetadataList = inDocMetadataList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDocumentListRes getDocumentListRes = (GetDocumentListRes) o;
    return Objects.equals(this.jobId, getDocumentListRes.jobId) &&
        Objects.equals(this.jobIdExt, getDocumentListRes.jobIdExt) &&
        Objects.equals(this.docLogs, getDocumentListRes.docLogs) &&
        Objects.equals(this.documentList, getDocumentListRes.documentList) &&
        Objects.equals(this.document, getDocumentListRes.document) &&
        Objects.equals(this.inDocMetadata, getDocumentListRes.inDocMetadata) &&
        Objects.equals(this.inDocMetadataList, getDocumentListRes.inDocMetadataList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobId, jobIdExt, docLogs, documentList, document, inDocMetadata, inDocMetadataList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDocumentListRes {\n");
    
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    jobIdExt: ").append(toIndentedString(jobIdExt)).append("\n");
    sb.append("    docLogs: ").append(toIndentedString(docLogs)).append("\n");
    sb.append("    documentList: ").append(toIndentedString(documentList)).append("\n");
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    inDocMetadata: ").append(toIndentedString(inDocMetadata)).append("\n");
    sb.append("    inDocMetadataList: ").append(toIndentedString(inDocMetadataList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

