/*
 * Pdf4me
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import model.UserPreference;

/**
 * GetUserPrefRes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-02T11:08:16.145Z")
public class GetUserPrefRes {
  @SerializedName("userPreferences")
  private List<UserPreference> userPreferences = null;

  public GetUserPrefRes userPreferences(List<UserPreference> userPreferences) {
    this.userPreferences = userPreferences;
    return this;
  }

  public GetUserPrefRes addUserPreferencesItem(UserPreference userPreferencesItem) {
    if (this.userPreferences == null) {
      this.userPreferences = new ArrayList<UserPreference>();
    }
    this.userPreferences.add(userPreferencesItem);
    return this;
  }

  /**
   * Get userPreferences
   * 
   * @return userPreferences
   **/
  @ApiModelProperty(value = "")
  public List<UserPreference> getUserPreferences() {
    return userPreferences;
  }

  public void setUserPreferences(List<UserPreference> userPreferences) {
    this.userPreferences = userPreferences;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetUserPrefRes getUserPrefRes = (GetUserPrefRes) o;
    return Objects.equals(this.userPreferences, getUserPrefRes.userPreferences);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userPreferences);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUserPrefRes {\n");

    sb.append("    userPreferences: ").append(toIndentedString(userPreferences)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
