/*
 * Pdf4me
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import model.KeyValuePairStringObject;

/**
 * IntegrationConfig
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-25T12:07:57.015+01:00")
public class IntegrationConfig {
  @SerializedName("configParams")
  private List<KeyValuePairStringObject> configParams = null;

  public IntegrationConfig configParams(List<KeyValuePairStringObject> configParams) {
    this.configParams = configParams;
    return this;
  }

  public IntegrationConfig addConfigParamsItem(KeyValuePairStringObject configParamsItem) {
    if (this.configParams == null) {
      this.configParams = new ArrayList<KeyValuePairStringObject>();
    }
    this.configParams.add(configParamsItem);
    return this;
  }

   /**
   * Get configParams
   * @return configParams
  **/
  @ApiModelProperty(value = "")
  public List<KeyValuePairStringObject> getConfigParams() {
    return configParams;
  }

  public void setConfigParams(List<KeyValuePairStringObject> configParams) {
    this.configParams = configParams;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationConfig integrationConfig = (IntegrationConfig) o;
    return Objects.equals(this.configParams, integrationConfig.configParams);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configParams);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationConfig {\n");
    
    sb.append("    configParams: ").append(toIndentedString(configParams)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

