/*
 * Pdf4me
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Machine
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-02T11:08:16.145Z")
public class Machine {
  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("machineIdExt")
  private String machineIdExt = null;

  @SerializedName("machineName")
  private String machineName = null;

  @SerializedName("lastUpdate")
  private OffsetDateTime lastUpdate = null;

  public Machine active(Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * 
   * @return active
   **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Machine enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * 
   * @return enabled
   **/
  @ApiModelProperty(value = "")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public Machine machineIdExt(String machineIdExt) {
    this.machineIdExt = machineIdExt;
    return this;
  }

  /**
   * Get machineIdExt
   * 
   * @return machineIdExt
   **/
  @ApiModelProperty(value = "")
  public String getMachineIdExt() {
    return machineIdExt;
  }

  public void setMachineIdExt(String machineIdExt) {
    this.machineIdExt = machineIdExt;
  }

  public Machine machineName(String machineName) {
    this.machineName = machineName;
    return this;
  }

  /**
   * Get machineName
   * 
   * @return machineName
   **/
  @ApiModelProperty(value = "")
  public String getMachineName() {
    return machineName;
  }

  public void setMachineName(String machineName) {
    this.machineName = machineName;
  }

  public Machine lastUpdate(OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
    return this;
  }

  /**
   * Get lastUpdate
   * 
   * @return lastUpdate
   **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Machine machine = (Machine) o;
    return Objects.equals(this.active, machine.active) && Objects.equals(this.enabled, machine.enabled)
        && Objects.equals(this.machineIdExt, machine.machineIdExt)
        && Objects.equals(this.machineName, machine.machineName) && Objects.equals(this.lastUpdate, machine.lastUpdate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, enabled, machineIdExt, machineName, lastUpdate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Machine {\n");

    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    machineIdExt: ").append(toIndentedString(machineIdExt)).append("\n");
    sb.append("    machineName: ").append(toIndentedString(machineName)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
