/*
 * Pdf4me
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MailingConfig
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-02T11:08:16.145Z")
public class MailingConfig {
  @SerializedName("print")
  private Boolean print = null;

  @SerializedName("archive")
  private Boolean archive = null;

  @SerializedName("printPoolName")
  private String printPoolName = null;

  @SerializedName("productionSession")
  private String productionSession = null;

  public MailingConfig print(Boolean print) {
    this.print = print;
    return this;
  }

  /**
   * Get print
   * 
   * @return print
   **/
  @ApiModelProperty(value = "")
  public Boolean isPrint() {
    return print;
  }

  public void setPrint(Boolean print) {
    this.print = print;
  }

  public MailingConfig archive(Boolean archive) {
    this.archive = archive;
    return this;
  }

  /**
   * Get archive
   * 
   * @return archive
   **/
  @ApiModelProperty(value = "")
  public Boolean isArchive() {
    return archive;
  }

  public void setArchive(Boolean archive) {
    this.archive = archive;
  }

  public MailingConfig printPoolName(String printPoolName) {
    this.printPoolName = printPoolName;
    return this;
  }

  /**
   * Get printPoolName
   * 
   * @return printPoolName
   **/
  @ApiModelProperty(value = "")
  public String getPrintPoolName() {
    return printPoolName;
  }

  public void setPrintPoolName(String printPoolName) {
    this.printPoolName = printPoolName;
  }

  public MailingConfig productionSession(String productionSession) {
    this.productionSession = productionSession;
    return this;
  }

  /**
   * Get productionSession
   * 
   * @return productionSession
   **/
  @ApiModelProperty(value = "")
  public String getProductionSession() {
    return productionSession;
  }

  public void setProductionSession(String productionSession) {
    this.productionSession = productionSession;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailingConfig mailingConfig = (MailingConfig) o;
    return Objects.equals(this.print, mailingConfig.print) && Objects.equals(this.archive, mailingConfig.archive)
        && Objects.equals(this.printPoolName, mailingConfig.printPoolName)
        && Objects.equals(this.productionSession, mailingConfig.productionSession);
  }

  @Override
  public int hashCode() {
    return Objects.hash(print, archive, printPoolName, productionSession);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailingConfig {\n");

    sb.append("    print: ").append(toIndentedString(print)).append("\n");
    sb.append("    archive: ").append(toIndentedString(archive)).append("\n");
    sb.append("    printPoolName: ").append(toIndentedString(printPoolName)).append("\n");
    sb.append("    productionSession: ").append(toIndentedString(productionSession)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
