/*
 * Pdf4me
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import model.MergeField;

/**
 * MergeData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-02T11:08:16.145Z")
public class MergeData {
  @SerializedName("mergeFields")
  private List<MergeField> mergeFields = null;

  public MergeData mergeFields(List<MergeField> mergeFields) {
    this.mergeFields = mergeFields;
    return this;
  }

  public MergeData addMergeFieldsItem(MergeField mergeFieldsItem) {
    if (this.mergeFields == null) {
      this.mergeFields = new ArrayList<MergeField>();
    }
    this.mergeFields.add(mergeFieldsItem);
    return this;
  }

  /**
   * Get mergeFields
   * 
   * @return mergeFields
   **/
  @ApiModelProperty(value = "")
  public List<MergeField> getMergeFields() {
    return mergeFields;
  }

  public void setMergeFields(List<MergeField> mergeFields) {
    this.mergeFields = mergeFields;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MergeData mergeData = (MergeData) o;
    return Objects.equals(this.mergeFields, mergeData.mergeFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mergeFields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MergeData {\n");

    sb.append("    mergeFields: ").append(toIndentedString(mergeFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
