/*
 * Pdf4me
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PdfValidationEvent
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-25T12:07:57.015+01:00")
public class PdfValidationEvent {
  @SerializedName("pageNr")
  private Integer pageNr = null;

  @SerializedName("objectNr")
  private Integer objectNr = null;

  @SerializedName("errorCode")
  private String errorCode = null;

  @SerializedName("errorMessage")
  private String errorMessage = null;

  public PdfValidationEvent pageNr(Integer pageNr) {
    this.pageNr = pageNr;
    return this;
  }

   /**
   * Get pageNr
   * @return pageNr
  **/
  @ApiModelProperty(value = "")
  public Integer getPageNr() {
    return pageNr;
  }

  public void setPageNr(Integer pageNr) {
    this.pageNr = pageNr;
  }

  public PdfValidationEvent objectNr(Integer objectNr) {
    this.objectNr = objectNr;
    return this;
  }

   /**
   * Get objectNr
   * @return objectNr
  **/
  @ApiModelProperty(value = "")
  public Integer getObjectNr() {
    return objectNr;
  }

  public void setObjectNr(Integer objectNr) {
    this.objectNr = objectNr;
  }

  public PdfValidationEvent errorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @ApiModelProperty(value = "")
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }

  public PdfValidationEvent errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Get errorMessage
   * @return errorMessage
  **/
  @ApiModelProperty(value = "")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PdfValidationEvent pdfValidationEvent = (PdfValidationEvent) o;
    return Objects.equals(this.pageNr, pdfValidationEvent.pageNr) &&
        Objects.equals(this.objectNr, pdfValidationEvent.objectNr) &&
        Objects.equals(this.errorCode, pdfValidationEvent.errorCode) &&
        Objects.equals(this.errorMessage, pdfValidationEvent.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageNr, objectNr, errorCode, errorMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PdfValidationEvent {\n");
    
    sb.append("    pageNr: ").append(toIndentedString(pageNr)).append("\n");
    sb.append("    objectNr: ").append(toIndentedString(objectNr)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

