/*
 * Pdf4me
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RotateConfig
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-25T12:07:57.015+01:00")
public class RotateConfig {
  @SerializedName("angle")
  private Double angle = null;

  @SerializedName("originX")
  private Integer originX = null;

  @SerializedName("originY")
  private Integer originY = null;

  public RotateConfig angle(Double angle) {
    this.angle = angle;
    return this;
  }

   /**
   * Get angle
   * @return angle
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getAngle() {
    return angle;
  }

  public void setAngle(Double angle) {
    this.angle = angle;
  }

  public RotateConfig originX(Integer originX) {
    this.originX = originX;
    return this;
  }

   /**
   * Get originX
   * @return originX
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getOriginX() {
    return originX;
  }

  public void setOriginX(Integer originX) {
    this.originX = originX;
  }

  public RotateConfig originY(Integer originY) {
    this.originY = originY;
    return this;
  }

   /**
   * Get originY
   * @return originY
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getOriginY() {
    return originY;
  }

  public void setOriginY(Integer originY) {
    this.originY = originY;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RotateConfig rotateConfig = (RotateConfig) o;
    return Objects.equals(this.angle, rotateConfig.angle) &&
        Objects.equals(this.originX, rotateConfig.originX) &&
        Objects.equals(this.originY, rotateConfig.originY);
  }

  @Override
  public int hashCode() {
    return Objects.hash(angle, originX, originY);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RotateConfig {\n");
    
    sb.append("    angle: ").append(toIndentedString(angle)).append("\n");
    sb.append("    originX: ").append(toIndentedString(originX)).append("\n");
    sb.append("    originY: ").append(toIndentedString(originY)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

