/*
 * Pdf4me
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import model.DocMetadata;
import model.Document;
import model.SubscriptionUsage;

/**
 * SplitRes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-02T11:08:16.145Z")
public class SplitRes {
  @SerializedName("documents")
  private List<Document> documents = null;

  @SerializedName("inDocMetadata")
  private List<DocMetadata> inDocMetadata = null;

  @SerializedName("traceId")
  private String traceId = null;

  @SerializedName("jobId")
  private String jobId = null;

  @SerializedName("subscriptionUsage")
  private SubscriptionUsage subscriptionUsage = null;

  public SplitRes documents(List<Document> documents) {
    this.documents = documents;
    return this;
  }

  public SplitRes addDocumentsItem(Document documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<Document>();
    }
    this.documents.add(documentsItem);
    return this;
  }

  /**
   * Get documents
   * 
   * @return documents
   **/
  @ApiModelProperty(value = "")
  public List<Document> getDocuments() {
    return documents;
  }

  public void setDocuments(List<Document> documents) {
    this.documents = documents;
  }

  public SplitRes inDocMetadata(List<DocMetadata> inDocMetadata) {
    this.inDocMetadata = inDocMetadata;
    return this;
  }

  public SplitRes addInDocMetadataItem(DocMetadata inDocMetadataItem) {
    if (this.inDocMetadata == null) {
      this.inDocMetadata = new ArrayList<DocMetadata>();
    }
    this.inDocMetadata.add(inDocMetadataItem);
    return this;
  }

  /**
   * Get inDocMetadata
   * 
   * @return inDocMetadata
   **/
  @ApiModelProperty(value = "")
  public List<DocMetadata> getInDocMetadata() {
    return inDocMetadata;
  }

  public void setInDocMetadata(List<DocMetadata> inDocMetadata) {
    this.inDocMetadata = inDocMetadata;
  }

  public SplitRes traceId(String traceId) {
    this.traceId = traceId;
    return this;
  }

  /**
   * Get traceId
   * 
   * @return traceId
   **/
  @ApiModelProperty(value = "")
  public String getTraceId() {
    return traceId;
  }

  public void setTraceId(String traceId) {
    this.traceId = traceId;
  }

  public SplitRes jobId(String jobId) {
    this.jobId = jobId;
    return this;
  }

  /**
   * Get jobId
   * 
   * @return jobId
   **/
  @ApiModelProperty(value = "")
  public String getJobId() {
    return jobId;
  }

  public void setJobId(String jobId) {
    this.jobId = jobId;
  }

  public SplitRes subscriptionUsage(SubscriptionUsage subscriptionUsage) {
    this.subscriptionUsage = subscriptionUsage;
    return this;
  }

  /**
   * Get subscriptionUsage
   * 
   * @return subscriptionUsage
   **/
  @ApiModelProperty(value = "")
  public SubscriptionUsage getSubscriptionUsage() {
    return subscriptionUsage;
  }

  public void setSubscriptionUsage(SubscriptionUsage subscriptionUsage) {
    this.subscriptionUsage = subscriptionUsage;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SplitRes splitRes = (SplitRes) o;
    return Objects.equals(this.documents, splitRes.documents)
        && Objects.equals(this.inDocMetadata, splitRes.inDocMetadata) && Objects.equals(this.traceId, splitRes.traceId)
        && Objects.equals(this.jobId, splitRes.jobId)
        && Objects.equals(this.subscriptionUsage, splitRes.subscriptionUsage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documents, inDocMetadata, traceId, jobId, subscriptionUsage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SplitRes {\n");

    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("    inDocMetadata: ").append(toIndentedString(inDocMetadata)).append("\n");
    sb.append("    traceId: ").append(toIndentedString(traceId)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    subscriptionUsage: ").append(toIndentedString(subscriptionUsage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
