/*
 * Pdf4me
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import model.Document;
import model.SplitByBarcodeAction;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SplitByBarcodeReq
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-02T11:08:16.145Z")
public class SplitByBarcodeReq {
  @SerializedName("document")
  private Document document = null;

  @SerializedName("splitByBarcodeAction")
  private SplitByBarcodeAction splitByBarcodeAction = null;

  @SerializedName("ipAddress")
  private String ipAddress = null;

  @SerializedName("jobId")
  private String jobId = null;

  @SerializedName("jobIdExt")
  private String jobIdExt = null;

  @SerializedName("integrations")
  private List<String> integrations = null;

  public SplitByBarcodeReq document(Document document) {
    this.document = document;
    return this;
  }

  /**
   * Get document
   * 
   * @return document
   **/
  @ApiModelProperty(required = true, value = "")
  public Document getDocument() {
    return document;
  }

  public void setDocument(Document document) {
    this.document = document;
  }

  public SplitByBarcodeReq splitByBarcodeAction(SplitByBarcodeAction splitByBarcodeAction) {
    this.splitByBarcodeAction = splitByBarcodeAction;
    return this;
  }

  /**
   * Get splitByBarcodeAction
   * 
   * @return splitByBarcodeAction
   **/
  @ApiModelProperty(value = "")
  public SplitByBarcodeAction getSplitByBarcodeAction() {
    return splitByBarcodeAction;
  }

  public void setSplitByBarcodeAction(SplitByBarcodeAction splitByBarcodeAction) {
    this.splitByBarcodeAction = splitByBarcodeAction;
  }

  public SplitByBarcodeReq ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

  /**
   * Get ipAddress
   * 
   * @return ipAddress
   **/
  @ApiModelProperty(value = "")
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  public SplitByBarcodeReq jobId(String jobId) {
    this.jobId = jobId;
    return this;
  }

  /**
   * Get jobId
   * 
   * @return jobId
   **/
  @ApiModelProperty(value = "")
  public String getJobId() {
    return jobId;
  }

  public void setJobId(String jobId) {
    this.jobId = jobId;
  }

  public SplitByBarcodeReq jobIdExt(String jobIdExt) {
    this.jobIdExt = jobIdExt;
    return this;
  }

  /**
   * Get jobIdExt
   * 
   * @return jobIdExt
   **/
  @ApiModelProperty(value = "")
  public String getJobIdExt() {
    return jobIdExt;
  }

  public void setJobIdExt(String jobIdExt) {
    this.jobIdExt = jobIdExt;
  }

  public SplitByBarcodeReq integrations(List<String> integrations) {
    this.integrations = integrations;
    return this;
  }

  public SplitByBarcodeReq addIntegrationsItem(String integrationsItem) {
    if (this.integrations == null) {
      this.integrations = new ArrayList<String>();
    }
    this.integrations.add(integrationsItem);
    return this;
  }

  /**
   * Get integrations
   * 
   * @return integrations
   **/
  @ApiModelProperty(value = "")
  public List<String> getIntegrations() {
    return integrations;
  }

  public void setIntegrations(List<String> integrations) {
    this.integrations = integrations;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SplitByBarcodeReq splitByBarcodeReq = (SplitByBarcodeReq) o;
    return Objects.equals(this.document, splitByBarcodeReq.document)
        && Objects.equals(this.splitByBarcodeAction, splitByBarcodeReq.splitByBarcodeAction)
        && Objects.equals(this.ipAddress, splitByBarcodeReq.ipAddress)
        && Objects.equals(this.jobId, splitByBarcodeReq.jobId)
        && Objects.equals(this.jobIdExt, splitByBarcodeReq.jobIdExt)
        && Objects.equals(this.integrations, splitByBarcodeReq.integrations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(document, splitByBarcodeAction, ipAddress, jobId, jobIdExt, integrations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SplitByBarcodeReq {\n");

    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    splitByBarcodeAction: ").append(toIndentedString(splitByBarcodeAction)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    jobIdExt: ").append(toIndentedString(jobIdExt)).append("\n");
    sb.append("    integrations: ").append(toIndentedString(integrations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
