/*
 * Pdf4me
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import model.UsageSubscription;

/**
 * UsageSubscriptionRes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-25T12:07:57.015+01:00")
public class UsageSubscriptionRes {
  @SerializedName("usageSubscriptionList")
  private List<UsageSubscription> usageSubscriptionList = null;

  @SerializedName("traceId")
  private String traceId = null;

  @SerializedName("jobId")
  private String jobId = null;

  public UsageSubscriptionRes usageSubscriptionList(List<UsageSubscription> usageSubscriptionList) {
    this.usageSubscriptionList = usageSubscriptionList;
    return this;
  }

  public UsageSubscriptionRes addUsageSubscriptionListItem(UsageSubscription usageSubscriptionListItem) {
    if (this.usageSubscriptionList == null) {
      this.usageSubscriptionList = new ArrayList<UsageSubscription>();
    }
    this.usageSubscriptionList.add(usageSubscriptionListItem);
    return this;
  }

   /**
   * Get usageSubscriptionList
   * @return usageSubscriptionList
  **/
  @ApiModelProperty(value = "")
  public List<UsageSubscription> getUsageSubscriptionList() {
    return usageSubscriptionList;
  }

  public void setUsageSubscriptionList(List<UsageSubscription> usageSubscriptionList) {
    this.usageSubscriptionList = usageSubscriptionList;
  }

  public UsageSubscriptionRes traceId(String traceId) {
    this.traceId = traceId;
    return this;
  }

   /**
   * Get traceId
   * @return traceId
  **/
  @ApiModelProperty(value = "")
  public String getTraceId() {
    return traceId;
  }

  public void setTraceId(String traceId) {
    this.traceId = traceId;
  }

  public UsageSubscriptionRes jobId(String jobId) {
    this.jobId = jobId;
    return this;
  }

   /**
   * Get jobId
   * @return jobId
  **/
  @ApiModelProperty(value = "")
  public String getJobId() {
    return jobId;
  }

  public void setJobId(String jobId) {
    this.jobId = jobId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageSubscriptionRes usageSubscriptionRes = (UsageSubscriptionRes) o;
    return Objects.equals(this.usageSubscriptionList, usageSubscriptionRes.usageSubscriptionList) &&
        Objects.equals(this.traceId, usageSubscriptionRes.traceId) &&
        Objects.equals(this.jobId, usageSubscriptionRes.jobId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usageSubscriptionList, traceId, jobId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageSubscriptionRes {\n");
    
    sb.append("    usageSubscriptionList: ").append(toIndentedString(usageSubscriptionList)).append("\n");
    sb.append("    traceId: ").append(toIndentedString(traceId)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

